"""initial schema

Revision ID: dad0675150f5
Revises: 
Create Date: 2026-10-08 20:08:47.207630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dad0675150f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('ACADEMIC', 'SPORTS', 'VOLUNTEER', 'HOBBY', 'ETC', name='clubcategory', native_enum=False, length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('club_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'ON_GOING', 'COMPLETE', 'CANCELLING', 'CANCELLED', name='eventstatus', native_enum=False, length=32), nullable=False),
    sa.Column('event_type', sa.Enum('MT', 'WELCOME', 'PICNIC', 'ACADEMIC', 'WORKSHOP', 'ETC', name='eventtype', native_enum=False, length=32), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expected_headcount', sa.Integer(), nullable=True),
    sa.Column('budget_total', sa.Integer(), nullable=True),
    sa.Column('fee_per_person', sa.Integer(), nullable=True),
    sa.Column('plan_warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('plan_excluded_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='행사'
    )
    op.create_index('ix_events_club_status', 'events', ['club_id', 'status'], unique=False)
    op.create_table('members',
    sa.Column('club_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'MEMBER', name='memberrole', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', name='memberstatus', native_enum=False, length=32), nullable=False),
    sa.Column('student_no', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('notify_approval_pending', sa.Boolean(), nullable=False),
    sa.Column('notify_step_delay', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'email', name='uq_members_club_email')
    )
    op.create_index(op.f('ix_members_club_id'), 'members', ['club_id'], unique=False)
    op.create_table('agent_log',
    sa.Column('club_id', sa.String(length=26), nullable=False),
    sa.Column('event_id', sa.String(length=26), nullable=True),
    sa.Column('feature', sa.Enum('PLANNING', 'RETRIEVAL', 'OPERATIONS', name='agentfeature', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='agentrunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_log_club_id'), 'agent_log', ['club_id'], unique=False)
    op.create_table('auth',
    sa.Column('member_id', sa.String(length=26), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'GOOGLE', 'KAKAO', name='authprovider', native_enum=False, length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_member_id'), 'auth', ['member_id'], unique=False)
    op.create_table('conversations',
    sa.Column('member_id', sa.String(length=26), nullable=False),
    sa.Column('event_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_event_id'), 'conversations', ['event_id'], unique=False)
    op.create_index(op.f('ix_conversations_member_id'), 'conversations', ['member_id'], unique=False)
    op.create_table('participants',
    sa.Column('event_id', sa.String(length=26), nullable=False),
    sa.Column('member_id', sa.String(length=26), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'member_id', name='uq_participants_event_member')
    )
    op.create_table('records',
    sa.Column('club_id', sa.String(length=26), nullable=False),
    sa.Column('event_id', sa.String(length=26), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('XLSX', 'CSV', 'HWP', 'PDF', 'IMAGE', name='recordfiletype', native_enum=False, length=32), nullable=False),
    sa.Column('category', sa.Enum('LEDGER', 'ETC', 'RULES', 'EVENT_HISTORY', name='recordcategory', native_enum=False, length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('parse_status', sa.Enum('QUEUED', 'PARSING', 'NEEDS_REVIEW', 'COMPLETED', 'INDEXED', 'FAILED', name='recordparsestatus', native_enum=False, length=32), nullable=False),
    sa.Column('parse_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('parse_error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='동아리 기록 원본 메타데이터'
    )
    op.create_index('ix_records_club_category', 'records', ['club_id', 'category'], unique=False)
    op.create_table('steps',
    sa.Column('event_id', sa.String(length=26), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('PREPARATION', 'RECRUITING', 'EXECUTION', 'CANCELLATION', name='stepphase', native_enum=False, length=32), nullable=False),
    sa.Column('code', sa.Enum('ASSIGN_ROLES', 'RESEARCH_VENUE', 'DEMAND_SURVEY', 'RECRUIT_NOTICE', 'CHECK_RESPONSES', 'CONFIRM_DETAILS', 'BOOK_VENUE', 'COLLECT_FEES', 'PRE_EVENT_NOTICE', 'EVENT_DAY', 'SETTLE_EXPENSES', 'REFUND_FEES', 'RECORD_FEEDBACK', 'CANCEL_NOTIFY_PARTICIPANTS', 'CANCEL_VENUE', 'CANCEL_REFUND', 'CANCEL_RECORD', name='stepcode', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.Enum('AI', 'APPROVAL_REQUIRED', 'MANUAL', name='stepactor', native_enum=False, length=32), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'step_order', deferrable=True, initially='DEFERRED', name='uq_steps_event_order')
    )
    op.create_table('actions',
    sa.Column('event_id', sa.String(length=26), nullable=False),
    sa.Column('step_id', sa.String(length=26), nullable=True),
    sa.Column('type', sa.Enum('EXTERNAL_SEND', 'TRANSFER', 'EXPENSE', 'CONTRACT', 'NOTICE', 'CONFIRMATION', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('irreversible', sa.Boolean(), nullable=False),
    sa.Column('approve_needed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'DONE', 'FAILED', name='actionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('deny_reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='승인·실행 대상 행동'
    )
    op.create_index('ix_actions_event_status', 'actions', ['event_id', 'status'], unique=False)
    op.create_index(op.f('ix_actions_step_id'), 'actions', ['step_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=26), nullable=True),
    sa.Column('step_id', sa.String(length=26), nullable=True),
    sa.Column('action_id', sa.String(length=26), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_messages_conversation_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_index(op.f('ix_actions_step_id'), table_name='actions')
    op.drop_index('ix_actions_event_status', table_name='actions')
    op.drop_table('actions')
    op.drop_table('steps')
    op.drop_index('ix_records_club_category', table_name='records')
    op.drop_table('records')
    op.drop_table('participants')
    op.drop_index(op.f('ix_conversations_member_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_event_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_auth_member_id'), table_name='auth')
    op.drop_table('auth')
    op.drop_index(op.f('ix_agent_log_club_id'), table_name='agent_log')
    op.drop_table('agent_log')
    op.drop_index(op.f('ix_members_club_id'), table_name='members')
    op.drop_table('members')
    op.drop_index('ix_events_club_status', table_name='events')
    op.drop_table('events')
    op.drop_table('clubs')
    # ### end Alembic commands ###
