/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Event Actions */
        get: operations["list_event_actions_api_v1_events__event_id__actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Event Steps */
        get: operations["list_event_steps_api_v1_events__event_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionListResponse */
        ActionListResponse: {
            /** Data */
            data: components["schemas"]["ActionOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /**
         * ActionOption
         * @description CONFIRMATION 카드의 선택 버튼 하나.
         */
        ActionOption: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** ActionOut */
        ActionOut: {
            /** Id */
            id: string;
            type: components["schemas"]["ActionType"];
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string | null;
            /** Irreversible */
            irreversible: boolean;
            /** Approveneeded */
            approveNeeded: boolean;
            status: components["schemas"]["ActionStatus"];
            /** Amount */
            amount: number | null;
            /** Duedate */
            dueDate: string | null;
            /** Stepid */
            stepId: string | null;
            /** Stepname */
            stepName: string | null;
            /** Resolvedat */
            resolvedAt: string | null;
            resolvedBy: components["schemas"]["ResolvedBy"] | null;
            /** Denyreason */
            denyReason: string | null;
            /** Options */
            options: components["schemas"]["ActionOption"][] | null;
            /** Allowmanual */
            allowManual: boolean | null;
            /** Canapprove */
            canApprove: boolean;
        };
        /**
         * ActionStatus
         * @description PENDING → APPROVED → DONE / FAILED, 또는 PENDING → DENIED.
         *
         *     approve_needed=False인 행동은 APPROVED를 거치지 않고 바로 DONE이 된다.
         * @enum {string}
         */
        ActionStatus: "PENDING" | "APPROVED" | "DENIED" | "DONE" | "FAILED";
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "EXTERNAL_SEND" | "TRANSFER" | "EXPENSE" | "CONTRACT" | "NOTICE" | "CONFIRMATION";
        /** DoneActionOut */
        DoneActionOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            status: components["schemas"]["ActionStatus"];
        };
        /** EventListResponse */
        EventListResponse: {
            /** Data */
            data: components["schemas"]["EventOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            status: components["schemas"]["EventStatus"];
            /** Startdate */
            startDate: string | null;
            /** Enddate */
            endDate: string | null;
            /** Dday */
            dday: number | null;
            /** Currentstepname */
            currentStepName: string | null;
            /** Stepprogress */
            stepProgress: components["schemas"]["StepProgressOut"][];
            /** Pendingapprovalcount */
            pendingApprovalCount: number;
            /** Payment */
            payment: unknown | null;
            /** Budget */
            budget: unknown | null;
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "PLANNING" | "ON_GOING" | "COMPLETE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MemberRole
         * @enum {string}
         */
        MemberRole: "OWNER" | "MANAGER" | "MEMBER";
        /** PageMeta */
        PageMeta: {
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Totalcount */
            totalCount: number;
        };
        /** RemainingActionOut */
        RemainingActionOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            status: components["schemas"]["ActionStatus"];
            /** Approveneeded */
            approveNeeded: boolean;
        };
        /**
         * ResolvedBy
         * @description 승인·거절·확인요청을 처리한 동아리원.
         */
        ResolvedBy: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["MemberRole"];
        };
        /**
         * StepActor
         * @enum {string}
         */
        StepActor: "AI" | "APPROVAL_REQUIRED" | "MANUAL";
        /** StepListResponse */
        StepListResponse: {
            /** Data */
            data: components["schemas"]["StepOut"][];
            /** Meta */
            meta?: null;
        };
        /** StepOut */
        StepOut: {
            /** Id */
            id: string;
            /** Steporder */
            stepOrder: number;
            /** Name */
            name: string;
            actor: components["schemas"]["StepActor"];
            state: components["schemas"]["StepState"];
            /** Startsat */
            startsAt: string | null;
            /** Deadline */
            deadline: string | null;
            /** Completedcount */
            completedCount: number;
            /** Totalactioncount */
            totalActionCount: number;
            /** Completedat */
            completedAt: string | null;
            /** Doneactions */
            doneActions: components["schemas"]["DoneActionOut"][];
            /** Remainingactions */
            remainingActions: components["schemas"]["RemainingActionOut"][];
        };
        /** StepProgressOut */
        StepProgressOut: {
            /** Steporder */
            stepOrder: number;
            state: components["schemas"]["StepState"];
        };
        /**
         * StepState
         * @description Step.completed_at으로부터 서버가 계산하는 진행 상태. DB에 저장하지 않는다.
         * @enum {string}
         */
        StepState: "DONE" | "CURRENT" | "TODO";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                clubId?: string | null;
                status?: components["schemas"]["EventStatus"] | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_event_actions_api_v1_events__event_id__actions_get: {
        parameters: {
            query?: {
                /** @description 쉼표로 여러 개. 예: PENDING, APPROVED,DONE,DENIED */
                status?: string | null;
                /** @description 이 유형만 조회 */
                type?: components["schemas"]["ActionType"] | null;
                /** @description 이 유형만 제외 */
                excludeType?: components["schemas"]["ActionType"] | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_event_steps_api_v1_events__event_id__steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
